# This workflow will build and test the dockermi Go project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.20', '1.21' ]
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o dockermi main.go

      - name: Test
        run: go test -v pkg/dockermi_test.go
